### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by sunnlife1978** [jhgjeraker/rnc-color-stretch#1]
Hello, 
Thank you for your python script. I also have a lot of trouble with davinci (just install it ....)
I'm trying your script in a python 3.7 environment (the only one where I can install opencv....) and when I try the --help option I get this error message:
`Traceback (most recent call last):
  File "rnc_color_stretch.py", line 205, in <module>
    def histogram(img: np.ndarray, channel: int) -> tuple[np.ndarray, np.ndarray]:
TypeError: 'type' object is not subscriptable`
Can you please help me to solve it.
Thanks 
Alex

**Comment by sunnlife1978** [comment]
It's good !!! I create a python 3.9 environment and everything is good !!!!

**Comment by jhgjeraker** [comment]
> It's good !!! I create a python 3.9 environment and everything is good !!!!

Hello there.

No worries, I'm glad you solved it!
This problem is caused by Python 3.7 (and 3.8?) not supporting proper typing, especially subscripts like `list[str]` or `tuple[str, int]`. There are workarounds to support older versions of Python, but 3.7 is end-of-life quite soon, so I probably won't add them unless it becomes a huge problem.

Cheers!
